{
  "uid" : "c386c62259017cba",
  "name" : "test_returns_true",
  "fullName" : "tests.brownie.token.tests.test_approve#test_returns_true",
  "historyId" : "83e76b6e4e37ba690728d80678312137",
  "time" : {
    "start" : 1642031186983,
    "stop" : 1642031186983,
    "duration" : 0
  },
  "status" : "broken",
  "statusMessage" : "ValueError: connection already closed",
  "statusTrace" : "brownie_project = <Project 'TokenProject'>\naccounts = <brownie.network.account.Accounts object at 0x7fae302657f0>\n\n    @pytest.fixture(scope=\"module\")\n    def token(brownie_project, accounts):\n>       return brownie_project.Token.deploy(\"Test Token\", \"TST\", 18, 1e21, {'from': accounts[0]})\n\ntests/brownie/token/tests/conftest.py:49: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n../../../.local/share/virtualenvs/neon-compatibility-g882AfFF/lib/python3.8/site-packages/brownie/network/contract.py:600: in __call__\n    return tx[\"from\"].deploy(\n../../../.local/share/virtualenvs/neon-compatibility-g882AfFF/lib/python3.8/site-packages/brownie/network/account.py:508: in deploy\n    receipt, exc = self._make_transaction(\n../../../.local/share/virtualenvs/neon-compatibility-g882AfFF/lib/python3.8/site-packages/brownie/network/account.py:725: in _make_transaction\n    raise VirtualMachineError(e) from None\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = VirtualMachineError(ValueError({'code': -32000, 'message': 'connection already closed'}))\nexc = {'code': -32000, 'message': 'connection already closed'}\n\n    def __init__(self, exc: ValueError) -> None:\n        try:\n            exc = exc.args[0]\n        except Exception:\n            pass\n    \n        if isinstance(exc, dict) and \"message\" in exc:\n            if \"data\" not in exc:\n>               raise ValueError(exc[\"message\"]) from None\nE               ValueError: connection already closed\n\n../../../.local/share/virtualenvs/neon-compatibility-g882AfFF/lib/python3.8/site-packages/brownie/exceptions.py:85: ValueError",
  "flaky" : false,
  "newFailed" : false,
  "newBroken" : false,
  "newPassed" : false,
  "retriesCount" : 0,
  "retriesStatusChange" : false,
  "beforeStages" : [ {
    "name" : "configure_neon_network",
    "time" : {
      "start" : 1642031167582,
      "stop" : 1642031167582,
      "duration" : 0
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "attachmentsCount" : 0,
    "stepsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  }, {
    "name" : "brownie_project",
    "time" : {
      "start" : 1642031168838,
      "stop" : 1642031184355,
      "duration" : 15517
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "attachmentsCount" : 0,
    "stepsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  }, {
    "name" : "accounts",
    "time" : {
      "start" : 1642031185279,
      "stop" : 1642031185605,
      "duration" : 326
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "attachmentsCount" : 0,
    "stepsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  }, {
    "name" : "setup_env",
    "time" : {
      "start" : 1642031185279,
      "stop" : 1642031185279,
      "duration" : 0
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "attachmentsCount" : 0,
    "stepsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  }, {
    "name" : "token",
    "time" : {
      "start" : 1642031185605,
      "stop" : 1642031186159,
      "duration" : 554
    },
    "status" : "broken",
    "statusMessage" : "ValueError: connection already closed\n",
    "statusTrace" : "  File \"/home/runner/.local/share/virtualenvs/neon-compatibility-g882AfFF/lib/python3.8/site-packages/pluggy/_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"/home/runner/.local/share/virtualenvs/neon-compatibility-g882AfFF/lib/python3.8/site-packages/_pytest/fixtures.py\", line 1126, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/home/runner/.local/share/virtualenvs/neon-compatibility-g882AfFF/lib/python3.8/site-packages/_pytest/fixtures.py\", line 932, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"/home/runner/work/neon-compatibility/neon-compatibility/tests/brownie/token/tests/conftest.py\", line 49, in token\n    return brownie_project.Token.deploy(\"Test Token\", \"TST\", 18, 1e21, {'from': accounts[0]})\n  File \"/home/runner/.local/share/virtualenvs/neon-compatibility-g882AfFF/lib/python3.8/site-packages/brownie/network/contract.py\", line 600, in __call__\n    return tx[\"from\"].deploy(\n  File \"/home/runner/.local/share/virtualenvs/neon-compatibility-g882AfFF/lib/python3.8/site-packages/brownie/network/account.py\", line 508, in deploy\n    receipt, exc = self._make_transaction(\n  File \"/home/runner/.local/share/virtualenvs/neon-compatibility-g882AfFF/lib/python3.8/site-packages/brownie/network/account.py\", line 725, in _make_transaction\n    raise VirtualMachineError(e) from None\n  File \"/home/runner/.local/share/virtualenvs/neon-compatibility-g882AfFF/lib/python3.8/site-packages/brownie/exceptions.py\", line 85, in __init__\n    raise ValueError(exc[\"message\"]) from None\n",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "attachmentsCount" : 0,
    "stepsCount" : 0,
    "shouldDisplayMessage" : true,
    "hasContent" : true
  } ],
  "afterStages" : [ {
    "name" : "accounts::0",
    "time" : {
      "start" : 1642031256987,
      "stop" : 1642031256987,
      "duration" : 0
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "attachmentsCount" : 0,
    "stepsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  } ],
  "labels" : [ {
    "name" : "feature",
    "value" : "Brownie"
  }, {
    "name" : "parentSuite",
    "value" : "tests.brownie.token.tests"
  }, {
    "name" : "suite",
    "value" : "test_approve"
  }, {
    "name" : "host",
    "value" : "fv-az74-735"
  }, {
    "name" : "thread",
    "value" : "3663-MainThread"
  }, {
    "name" : "framework",
    "value" : "pytest"
  }, {
    "name" : "language",
    "value" : "cpython3"
  }, {
    "name" : "package",
    "value" : "tests.brownie.token.tests.test_approve"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ ],
  "links" : [ ],
  "hidden" : false,
  "retry" : false,
  "extra" : {
    "severity" : "normal",
    "retries" : [ ],
    "categories" : [ {
      "name" : "Test defects",
      "matchedStatuses" : [ ],
      "flaky" : false
    } ],
    "history" : {
      "statistic" : {
        "failed" : 0,
        "broken" : 89,
        "skipped" : 0,
        "passed" : 0,
        "unknown" : 0,
        "total" : 89
      },
      "items" : [ {
        "uid" : "61959daeb2e706",
        "reportUrl" : "https://neonlabsorg.github.io/neon-compatibility/476//#testresult/61959daeb2e706",
        "status" : "broken",
        "statusDetails" : "ValueError: connection already closed",
        "time" : {
          "start" : 1642028348918,
          "stop" : 1642028348918,
          "duration" : 0
        }
      }, {
        "uid" : "9ed5954b6a3d86dc",
        "reportUrl" : "https://neonlabsorg.github.io/neon-compatibility/474//#testresult/9ed5954b6a3d86dc",
        "status" : "broken",
        "statusDetails" : "ValueError: connection already closed",
        "time" : {
          "start" : 1642025671222,
          "stop" : 1642025671222,
          "duration" : 0
        }
      }, {
        "uid" : "a16d13a50a197278",
        "reportUrl" : "https://neonlabsorg.github.io/neon-compatibility/472//#testresult/a16d13a50a197278",
        "status" : "broken",
        "statusDetails" : "ValueError: connection already closed",
        "time" : {
          "start" : 1642018235943,
          "stop" : 1642018235943,
          "duration" : 0
        }
      }, {
        "uid" : "101ff11cd26160b1",
        "reportUrl" : "https://neonlabsorg.github.io/neon-compatibility/471//#testresult/101ff11cd26160b1",
        "status" : "broken",
        "statusDetails" : "ValueError: connection already closed",
        "time" : {
          "start" : 1642015603016,
          "stop" : 1642015603016,
          "duration" : 0
        }
      }, {
        "uid" : "a1bd02389c7324de",
        "reportUrl" : "https://neonlabsorg.github.io/neon-compatibility/470//#testresult/a1bd02389c7324de",
        "status" : "broken",
        "statusDetails" : "ValueError: connection already closed",
        "time" : {
          "start" : 1642014228819,
          "stop" : 1642014228819,
          "duration" : 0
        }
      }, {
        "uid" : "89bbe836047d8e80",
        "reportUrl" : "https://neonlabsorg.github.io/neon-compatibility/469//#testresult/89bbe836047d8e80",
        "status" : "broken",
        "statusDetails" : "ValueError: connection already closed",
        "time" : {
          "start" : 1642012910493,
          "stop" : 1642012910493,
          "duration" : 0
        }
      }, {
        "uid" : "c00a99e7ed3af2f",
        "reportUrl" : "https://neonlabsorg.github.io/neon-compatibility/468//#testresult/c00a99e7ed3af2f",
        "status" : "broken",
        "statusDetails" : "ValueError: connection already closed",
        "time" : {
          "start" : 1642011420595,
          "stop" : 1642011420595,
          "duration" : 0
        }
      }, {
        "uid" : "94cd5846b9b15a5",
        "reportUrl" : "https://neonlabsorg.github.io/neon-compatibility/466//#testresult/94cd5846b9b15a5",
        "status" : "broken",
        "statusDetails" : "brownie.exceptions.RPCRequestError: 'EthereumModel' object has no attribute 'debug_traceTransaction'",
        "time" : {
          "start" : 1641997956157,
          "stop" : 1641997958713,
          "duration" : 2556
        }
      }, {
        "uid" : "966b3c756f0cc3e",
        "reportUrl" : "https://neonlabsorg.github.io/neon-compatibility/465//#testresult/966b3c756f0cc3e",
        "status" : "broken",
        "statusDetails" : "brownie.exceptions.RPCRequestError: 'EthereumModel' object has no attribute 'debug_traceTransaction'",
        "time" : {
          "start" : 1641993718105,
          "stop" : 1641993720709,
          "duration" : 2604
        }
      }, {
        "uid" : "628b3f164eda54b6",
        "reportUrl" : "https://neonlabsorg.github.io/neon-compatibility/464//#testresult/628b3f164eda54b6",
        "status" : "broken",
        "statusDetails" : "brownie.exceptions.RPCRequestError: 'EthereumModel' object has no attribute 'debug_traceTransaction'",
        "time" : {
          "start" : 1641990977991,
          "stop" : 1641990980378,
          "duration" : 2387
        }
      }, {
        "uid" : "53a9856777875046",
        "reportUrl" : "https://neonlabsorg.github.io/neon-compatibility/463//#testresult/53a9856777875046",
        "status" : "broken",
        "statusDetails" : "brownie.exceptions.RPCRequestError: 'EthereumModel' object has no attribute 'debug_traceTransaction'",
        "time" : {
          "start" : 1641986338936,
          "stop" : 1641986340632,
          "duration" : 1696
        }
      }, {
        "uid" : "c33de290eecb8d78",
        "reportUrl" : "https://neonlabsorg.github.io/neon-compatibility/461//#testresult/c33de290eecb8d78",
        "status" : "broken",
        "statusDetails" : "ValueError: Gas estimation failed: 'HTTPConnectionPool(host='10.2.0.2', port=8899): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f18961e3b80>: Failed to establish a new connection: [Errno 111] Connection refused'))'. This transaction will likely revert. If you wish to broadcast, you must set the gas limit manually.",
        "time" : {
          "start" : 1641982477181,
          "stop" : 1641982477181,
          "duration" : 0
        }
      }, {
        "uid" : "7e1174656bfc81b5",
        "reportUrl" : "https://neonlabsorg.github.io/neon-compatibility/460//#testresult/7e1174656bfc81b5",
        "status" : "broken",
        "statusDetails" : "ValueError: Gas estimation failed: 'HTTPConnectionPool(host='10.2.0.2', port=8899): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f189611ea30>: Failed to establish a new connection: [Errno 111] Connection refused'))'. This transaction will likely revert. If you wish to broadcast, you must set the gas limit manually.",
        "time" : {
          "start" : 1641980266041,
          "stop" : 1641980266041,
          "duration" : 0
        }
      }, {
        "uid" : "b63abc7ab041717e",
        "reportUrl" : "https://neonlabsorg.github.io/neon-compatibility/459//#testresult/b63abc7ab041717e",
        "status" : "broken",
        "statusDetails" : "brownie.exceptions.RPCRequestError: 'EthereumModel' object has no attribute 'debug_traceTransaction'",
        "time" : {
          "start" : 1641975792629,
          "stop" : 1641975794745,
          "duration" : 2116
        }
      }, {
        "uid" : "90b86d0e4e8005b3",
        "reportUrl" : "https://neonlabsorg.github.io/neon-compatibility/458//#testresult/90b86d0e4e8005b3",
        "status" : "broken",
        "statusDetails" : "ValueError: Gas estimation failed: 'HTTPConnectionPool(host='10.2.0.2', port=8899): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f189611b8e0>: Failed to establish a new connection: [Errno 111] Connection refused'))'. This transaction will likely revert. If you wish to broadcast, you must set the gas limit manually.",
        "time" : {
          "start" : 1641974826027,
          "stop" : 1641974826027,
          "duration" : 0
        }
      }, {
        "uid" : "ee205d9e1270883c",
        "reportUrl" : "https://neonlabsorg.github.io/neon-compatibility/457//#testresult/ee205d9e1270883c",
        "status" : "broken",
        "statusDetails" : "ValueError: Gas estimation failed: 'HTTPConnectionPool(host='10.2.0.2', port=8899): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1895fcda90>: Failed to establish a new connection: [Errno 111] Connection refused'))'. This transaction will likely revert. If you wish to broadcast, you must set the gas limit manually.",
        "time" : {
          "start" : 1641974204540,
          "stop" : 1641974204540,
          "duration" : 0
        }
      }, {
        "uid" : "25f6d5196f14c9e3",
        "reportUrl" : "https://neonlabsorg.github.io/neon-compatibility/456//#testresult/25f6d5196f14c9e3",
        "status" : "broken",
        "statusDetails" : "requests.exceptions.ReadTimeout: HTTPConnectionPool(host='proxy.night.stand.neontest.xyz', port=80): Read timed out. (read timeout=30)",
        "time" : {
          "start" : 1641957703891,
          "stop" : 1641957703891,
          "duration" : 0
        }
      }, {
        "uid" : "cb4a2f4a6bb1ef19",
        "reportUrl" : "https://neonlabsorg.github.io/neon-compatibility/455//#testresult/cb4a2f4a6bb1ef19",
        "status" : "broken",
        "statusDetails" : "requests.exceptions.ReadTimeout: HTTPConnectionPool(host='proxy.night.stand.neontest.xyz', port=80): Read timed out. (read timeout=30)",
        "time" : {
          "start" : 1641951900229,
          "stop" : 1641951900229,
          "duration" : 0
        }
      }, {
        "uid" : "1152715266659ab9",
        "reportUrl" : "https://neonlabsorg.github.io/neon-compatibility/454//#testresult/1152715266659ab9",
        "status" : "broken",
        "statusDetails" : "requests.exceptions.ReadTimeout: HTTPConnectionPool(host='proxy.night.stand.neontest.xyz', port=80): Read timed out. (read timeout=30)",
        "time" : {
          "start" : 1641950378576,
          "stop" : 1641950378576,
          "duration" : 0
        }
      }, {
        "uid" : "72f4ff4e03e62053",
        "reportUrl" : "https://neonlabsorg.github.io/neon-compatibility/453//#testresult/72f4ff4e03e62053",
        "status" : "broken",
        "statusDetails" : "brownie.exceptions.RPCRequestError: 'EthereumModel' object has no attribute 'debug_traceTransaction'",
        "time" : {
          "start" : 1641947694928,
          "stop" : 1641947696620,
          "duration" : 1692
        }
      } ]
    },
    "tags" : [ ]
  },
  "source" : "c386c62259017cba.json",
  "parameterValues" : [ ]
}