{
  "uid" : "e45a73b91cde12a7",
  "name" : "non-compliant beacon",
  "fullName" : "non-compliant beacon",
  "historyId" : "220a8bc4cbb22f902a922325359b6dba",
  "time" : {
    "start" : 1640239120148,
    "stop" : 1640239122328,
    "duration" : 2180
  },
  "status" : "failed",
  "statusMessage" : "Wrong kind of exception received: expected 'Returned error: {\"id\":290,\"jsonrpc\":\"2.0\",\"error\":{\"code\":3,\"message\":\"\",\"data\":{\"stack\":\"ProviderError: \\\\n    at HttpProvider.request (/home/deploy/actions-runner/_work/neon-compatibility/neon-compatibility/node_modules/hardhat/src/internal/core/providers/http.ts:49:19)\\\\n    at LocalAccountsProvider.request (/home/deploy/actions-runner/_work/neon-compatibility/neon-compatibility/node_modules/hardhat/src/internal/core/providers/accounts.ts:162:36)\\\\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\\\\n    at Web3HTTPProviderAdapter._sendJsonRpcRequest (/home/deploy/actions-runner/_work/neon-compatibility/neon-compatibility/node_modules/@nomiclabs/hardhat-web3/src/web3-provider-adapter.ts:80:22)\",\"name\":\"ProviderError\"}}}' to equal 'revert'",
  "statusTrace" : "AssertionError: Wrong kind of exception received: expected 'Returned error: {\"id\":290,\"jsonrpc\":\"2.0\",\"error\":{\"code\":3,\"message\":\"\",\"data\":{\"stack\":\"ProviderError: \\\\n    at HttpProvider.request (/home/deploy/actions-runner/_work/neon-compatibility/neon-compatibility/node_modules/hardhat/src/internal/core/providers/http.ts:49:19)\\\\n    at LocalAccountsProvider.request (/home/deploy/actions-runner/_work/neon-compatibility/neon-compatibility/node_modules/hardhat/src/internal/core/providers/accounts.ts:162:36)\\\\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\\\\n    at Web3HTTPProviderAdapter._sendJsonRpcRequest (/home/deploy/actions-runner/_work/neon-compatibility/neon-compatibility/node_modules/@nomiclabs/hardhat-web3/src/web3-provider-adapter.ts:80:22)\",\"name\":\"ProviderError\"}}}' to equal 'revert'\n    at expectException (/home/deploy/actions-runner/_work/neon-compatibility/neon-compatibility/node_modules/@openzeppelin/test-helpers/src/expectRevert.js:20:30)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at Context.<anonymous> (test/proxy/beacon/BeaconProxy.test.js:34:7)",
  "flaky" : false,
  "newFailed" : false,
  "newBroken" : false,
  "newPassed" : false,
  "retriesCount" : 0,
  "retriesStatusChange" : false,
  "beforeStages" : [ {
    "time" : { },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  }, {
    "time" : { },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  } ],
  "afterStages" : [ ],
  "labels" : [ {
    "name" : "parentSuite",
    "value" : "Contract: BeaconProxy"
  }, {
    "name" : "suite",
    "value" : "bad beacon is not accepted"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ ],
  "links" : [ ],
  "hidden" : false,
  "retry" : false,
  "extra" : {
    "severity" : "normal",
    "retries" : [ ],
    "categories" : [ {
      "name" : "Product defects",
      "matchedStatuses" : [ ],
      "flaky" : false
    } ],
    "history" : {
      "statistic" : {
        "failed" : 2,
        "broken" : 1,
        "skipped" : 0,
        "passed" : 0,
        "unknown" : 0,
        "total" : 3
      },
      "items" : [ {
        "uid" : "dbb4006e6fd8f3e0",
        "reportUrl" : "https://neonlabsorg.github.io/neon-compatibility/feature/213-return-post-processing-of-allure-files-to-form-a-feature-story-line/303//#testresult/dbb4006e6fd8f3e0",
        "status" : "failed",
        "statusDetails" : "Wrong kind of exception received: expected 'Returned error: {\"id\":108,\"jsonrpc\":\"2.0\",\"error\":{\"code\":3,\"message\":\"\",\"data\":{\"stack\":\"ProviderError: \\\\n    at HttpProvider.request (/home/deploy/actions-runner/_work/neon-compatibility/neon-compatibility/node_modules/hardhat/src/internal/core/providers/http.ts:49:19)\\\\n    at LocalAccountsProvider.request (/home/deploy/actions-runner/_work/neon-compatibility/neon-compatibility/node_modules/hardhat/src/internal/core/providers/accounts.ts:162:36)\\\\n    at runMicrotasks (<anonymous>)\\\\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\\\\n    at Web3HTTPProviderAdapter._sendJsonRpcRequest (/home/deploy/actions-runner/_work/neon-compatibility/neon-compatibility/node_modules/@nomiclabs/hardhat-web3/src/web3-provider-adapter.ts:80:22)\",\"name\":\"ProviderError\"}}}' to equal 'revert'",
        "time" : {
          "start" : 1640238219972,
          "stop" : 1640238221859,
          "duration" : 1887
        }
      }, {
        "uid" : "d6a630b4cb8df2bb",
        "reportUrl" : "https://neonlabsorg.github.io/neon-compatibility/feature/213-return-post-processing-of-allure-files-to-form-a-feature-story-line/302//#testresult/d6a630b4cb8df2bb",
        "status" : "broken",
        "statusDetails" : "Returned error: HTTPConnectionPool(host='10.2.0.2', port=8899): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcc5e8f6160>: Failed to establish a new connection: [Errno 99] Cannot assign requested address'))",
        "time" : {
          "start" : 1640235280782,
          "stop" : 1640235280809,
          "duration" : 27
        }
      } ]
    },
    "tags" : [ ]
  },
  "source" : "e45a73b91cde12a7.json",
  "parameterValues" : [ ]
}